"""add preview_images

Revision ID: 4bdccf911959
Revises: a79d5ca48a90
Create Date: 2026-03-03 16:54:24.873842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdccf911959'
down_revision = 'a79d5ca48a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.drop_column('preview_images')

    # ### end Alembic commands ###
