"""add file_path column

Revision ID: a79d5ca48a90
Revises: 
Create Date: 2026-03-02 13:49:38.886726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79d5ca48a90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
