"""allow guest payments

Revision ID: e543f6f7f1be
Revises: cc100f53cf6d
Create Date: 2026-03-09 13:50:44.128445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e543f6f7f1be'
down_revision = 'cc100f53cf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_payment_pack",
            "pack",
            ["pack_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
